VERSION 1.0 CLASS
BEGIN
  MultiUse = -1  'True
END
Attribute VB_Name = "ISortable"
Attribute VB_GlobalNameSpace = False
Attribute VB_Creatable = False
Attribute VB_PredeclaredId = False
Attribute VB_Exposed = False
'https://analystcave.com/vba-implements-tutorial/
'https://github.com/Vitosh/VBA_personal

Option Explicit

'
' Metoda wykonuje sortowanie kolekcji zgodnie
'
Public Sub sort(items() As Variant)

End Sub

