VERSION 1.0 CLASS
BEGIN
  MultiUse = -1  'True
END
Attribute VB_Name = "ISwapable"
Attribute VB_GlobalNameSpace = False
Attribute VB_Creatable = False
Attribute VB_PredeclaredId = False
Attribute VB_Exposed = False
Option Explicit

'
'
'
Public Sub SwapObject(ByRef factorLeft As Object, ByRef factorRight As Object)

End Sub


Public Sub SwapValue(factorLeft As Variant, factorRight As Variant)

End Sub

